In [2]:
#import Numpy 
import numpy as np

In [3]:
#creating an Array Object
arr = np.array([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
#2d array 
arr2d = np.array([[1,2,3,4],
                 [5,6,7,8]])

In [8]:
print(arr2d)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
#printing array type of Object 
print(type(arr2d))

<class 'numpy.ndarray'>


In [10]:
#printing Dimenison of array
print(arr2d.ndim)

2


In [12]:
#printing Shape of Array 
print(arr2d.shape)

(2, 4)


In [13]:
#printing size of array
print(arr2d.size)

8


In [14]:
# Printing type of elements in array
print(arr2d.dtype)

int32


In [17]:
#creating array from list with type flot

arr1 = np.array([[1,2,3,4],
                 [5,6,7,8]], dtype = 'float')

In [18]:
arr1

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [19]:
#creating array from tuple
arr_tuple = np.array((2,3,4,5))

In [21]:
arr_tuple

array([2, 3, 4, 5])

In [24]:
#creating array with all element is zero 
arr_zero = np.zeros((3,4))

In [25]:
arr_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
# Create a constant value array of complex type
d = np.full((3,3) , 6 , dtype='complex')

In [27]:
d

array([[6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j]])

In [30]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

In [31]:
#slicing in array

In [32]:
temp = arr[:2 , ::2]

In [33]:
temp

array([[-1.,  0.],
       [ 4.,  6.]])

In [34]:
#add 1 to every element 
print(temp+1)

[[0. 1.]
 [5. 7.]]


In [35]:
#subtract 2 from every element
print(temp-3)

[[-4. -3.]
 [ 1.  3.]]


In [36]:
#multiply by 5 every element
print(temp*5)

[[-5.  0.]
 [20. 30.]]


In [37]:
#square of every element 
print(temp**2)

[[ 1.  0.]
 [16. 36.]]


In [38]:
# modify existing array
temp *= 2
print ("Doubled each element of original array:", temp)

Doubled each element of original array: [[-2.  0.]
 [ 8. 12.]]


In [40]:
#maximum element of the array 
print(arr.max())

12.0


In [41]:
#maximum element of the array row wise
print(arr.max(axis=1))

[ 4. 12.  8.  4.]


In [43]:
#maximum element of the array column wise
print(arr.max(axis=0))

[ 8.  2. 12.  8.]


In [44]:
#minimum elemet of the array
print(arr.min())

-7.0


In [45]:
#rowise minimum element 
print(arr.min(axis=1))

[-2.  -0.5  0.  -7. ]


In [47]:
#colunm wise minimum element
print(arr.min(axis=0 ))

[-2. -7.  0.  0.]


In [48]:
#sum of array element 
print(arr.sum())

43.1


In [49]:
#row wise sum of array element 
print(arr.sum(axis=1))

[ 4.  19.5 17.6  2. ]


In [50]:
#column wise sum of array element 
print(arr.sum(axis=0))

[11.6 -5.5 23.  14. ]


In [53]:
# cumulative sum along each row
print(arr.cumsum(axis=1))

[[-2.   0.   0.   4. ]
 [ 8.   7.5 19.5 19.5]
 [ 2.6  2.6  9.6 17.6]
 [ 3.  -4.   0.   2. ]]


In [54]:
a = np.array([[1,2] , 
             [3,4]])
b = np.array([[4,3] ,
             [2,1]])

In [55]:
# add arrays
print(a+b)

[[5 5]
 [5 5]]


In [56]:
# multiply arrays (elementwise multiplication)
print(a*b)

[[4 6]
 [6 4]]


In [57]:
# matrix multiplication dot product 
print(a.dot(b))
 

[[ 8  5]
 [20 13]]


In [58]:
# square root of array values
print(np.sqrt(a))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [60]:

# exponential values
print(np.exp(a))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [61]:
# create an array of sine values
print(np.sin(a))

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


In [63]:
# create an array of cos values
print(np.cos(a))

[[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]


In [65]:
# create an array of tan values
print(np.tan(a))

[[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]]
